### ISSUE TITLE
Missing informations for setup on Windows

### ISSUE THREAD

**Issue by BestNoob** [maniaplanet/dedicated-manager#5]
- how to get this to work with xampp ?
- is manialive required or is it usable with xaseco2 ?
- is composer needed to run this ?
- gettext needed or is it already included in xampp ?
- do i need redirection
- what do you mean with commandline ? linux ? what is with windows users ?
- what for an alias do i need to create ?
- do i need to set listening on port 81 and set Port 81 in the httpd-vhosts.conf ?
- how du i use the webmanager ? http://localhost:81/ or http://127.0.0.1/manager/

You have the half information here and another half information there ?  :roflol: 
http://wiki.maniaplanet.com/en/Dedicated_manager
https://github.com/maniaplanet/dedicated-manager

and another part of information is inside the readme file ?

**Comment by satanasdiabolo** [comment]
Hi Bestnoob,
here is the response to all your questions:
- This should work with xampp.
  Just extract the dedicated manager anywhere on your computer
- ManiaLive is not a requirement for the dedicated manager. The dedicated manager is not compatble with xaseco2 at the moment.
- You don't need composer if you get the latest release from here: https://github.com/maniaplanet/dedicated-manager/releases
- gettext is needed and included in xampp
- What do you mean with this question ?
- Command line on windows is the dos interface (cmd.exe)
- An Alias is a configuration that allows you to associate a folder on your computer to a path on your web server
  Here you have to create a link between the folder named "www" in the dedicated manager folder and http://127.0.0.1/manager/
  To do that, on the Xampp Control Panel:
  - click on "config" in the apache line
  - then on Apache (httpd.conf)
  - search the line with `<Directory "c:/xampp/htdocs">`
  - Just bellow this line put the following line

```
Alias /manager c:/path/to/the/dedicated/manager
<Directory c:/path/to/the/dedicated/manager>
  Options -Indexes +FollowSymLinks
  AllowOverride All
  Require all granted
</Directory>
```
- Restart Apache and you should be able to access to the manager with http://127.0.0.1/manager/
  - By default xampp should be listening on port 80, if this one is already used apache won't start
    You can change this port by clicking in your XAMPP Control Panel on "Config" then "Service and Port Settings"
    Then change Main Port on the Apache tab
  - You can use the manager with http://127.0.0.1/manager/
  - I'll fix this

I hope I've answered to all your questions
